package com.stupid.method.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.stupid.method.db.bean.TmpData;

import com.stupid.method.db.dao.TmpDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tmpDataDaoConfig;

    private final TmpDataDao tmpDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tmpDataDaoConfig = daoConfigMap.get(TmpDataDao.class).clone();
        tmpDataDaoConfig.initIdentityScope(type);

        tmpDataDao = new TmpDataDao(tmpDataDaoConfig, this);

        registerDao(TmpData.class, tmpDataDao);
    }
    
    public void clear() {
        tmpDataDaoConfig.getIdentityScope().clear();
    }

    public TmpDataDao getTmpDataDao() {
        return tmpDataDao;
    }

}
