package com.stupid.method.db.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TMP_DATA.
 */
public class TmpData {

    /** Not-null value. */
    private String Key;
    private String Value;
    private java.util.Date Date;

    public TmpData() {
    }

    public TmpData(String Key) {
        this.Key = Key;
    }

    public TmpData(String Key, String Value, java.util.Date Date) {
        this.Key = Key;
        this.Value = Value;
        this.Date = Date;
    }

    /** Not-null value. */
    public String getKey() {
        return Key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String Key) {
        this.Key = Key;
    }

    public String getValue() {
        return Value;
    }

    public void setValue(String Value) {
        this.Value = Value;
    }

    public java.util.Date getDate() {
        return Date;
    }

    public void setDate(java.util.Date Date) {
        this.Date = Date;
    }

}
